name: cloudinary_sdk
description: This is a dart package for Cloudinary API that allows you to upload and manage files in your cloudinary cloud.
version: 1.0.1+2
homepage: https://github.com/luis901101/cloudinary-sdk

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  crypto: ^2.1.5
